### ISSUE TITLE
API Tests - Hardcoded files

### ISSUE THREAD

**Issue by drlukeparry** [leap71/PicoGKRuntime#3]
The API Test mesh & images files are hardcoded and are not included in the release or repository.

**Comment by LinKayser** [comment]
Yes, this is true. In an ideal world, we would have lots of unit tests in the C++ API Test App. In practice, I use the APITest part only for testing new functions (as it's hard to debug across C#/C++ bounds) and all other testing is better done on the C# side. So I have no intention to spend much time on this at the moment. Maybe some day :)

**Comment by LinKayser** [comment]
Closing this, as no plan to fix. All relevant tests are on the PicoGK C# side, where we have all test files in the project.
