### ISSUE TITLE
Specifiying strPicoGKLibPath does not work

### ISSUE THREAD

**Issue by Niels-IO** [leap71/PicoGKRuntime#5]
Hi,

After building the runtime, I was not able to get it to run with the dylib inside the Dist folder as it is specified in the readme [here](https://github.com/leap71/PicoGK/blob/main/Documentation/Compiling_PicoGKRuntime.md#using-the-compiled-runtime).

After copying the dylib to the /usr/local/lib directory, it worked. 🙂

**Comment by LinKayser** [comment]
We are readying installers right now to remove all these issues. But we do use it like that all the time (to switch between development versions and the released version), so there must be some secondary issue that lead to it not working for you.
