### ISSUE TITLE
NaN numbers in LatticeBeam::fSdvFlatCone()

### ISSUE THREAD

**Issue by drlukeparry** [leap71/PicoGKRuntime#6]
On the following line, it is possible under rare occasions to get NaN due to round-off errors leading to strange artefacts in the signed distance field for the flat capped cone in the render lattice methods for beams.

https://github.com/leap71/PicoGKRuntime/blob/d5f5ac38ab1c2090fb47b4c4f700553dd2c912aa/Source/PicoGKLattice.h#L163C56-L163C56

` float x = std::sqrt(papa - paba * paba * baba); `

Although not in the original implementation by [Inigo ](https://www.shadertoy.com/view/tsSXzK)- it may be worth considering absolute values or lower-bound clipping within the square root.

**Comment by LinKayser** [comment]
Very true, and this was actually happening all the time, so the center of all flat-cap beams had a tiny hole down the center. Seems we only used round cap lattices in our code so far. Fixed in my latest check-in, by lower-bound clipping to zero.
